site_name: Notionary
site_url: https://mathisarends.github.io/notionary/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - scheme: default
      primary: black
      accent: indigo

extra_css:
  - assets/styles.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - Intro: index.md
  - Quickstart: quickstart.md

  - Documentation:
      - Page: page.md
      - Data Source:
        - data_source/index.md
      - Workspace:
        - workspace/index.md
      - Database: database.md
      - File Upload:
        - Overview: file_upload/index.md
        - Integration: file_upload/integration.md
        - Query: file_upload/query.md
        - Resolver: file_upload/resolver.md

      - Blocks:
          - Overview: blocks/blocks.md
          - Markdown Lookup:  blocks/markdown_lookup.md
          - Structured Ouput: blocks/structured_output.md
          - Breadcrumb: blocks/breadcrumb.md
          - Bulleted List: blocks/bulleted_list.md
          - Callout: blocks/callout.md
          - Code: blocks/code.md
          - Columns: blocks/column.md
          - Divider: blocks/divider.md
          - Embed: blocks/embed.md
          - Equation: blocks/equation.md
          - File: blocks/file.md
          - Heading: blocks/heading.md
          - Image: blocks/image.md
          - Numbered List: blocks/numbered_list.md
          - Paragraph: blocks/paragraph.md
          - PDF: blocks/pdf.md
          - Quote: blocks/quote.md
          - Rich Text: blocks/rich_text.md
          - Space: blocks/space.md
          - Table: blocks/table.md
          - Table of Contents: blocks/table_of_contents.md
          - Todo: blocks/todo.md
          - Toggle: blocks/toggle.md
          - Video: blocks/video.md

  - Shoutouts: shoutouts.md
  - Contributing: contributing.md

repo_url: https://github.com/mathisarends/notionary
repo_name: mathisarends/notionary

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
